program: main_infonce.py
data_dir: /data2/wangchangmiao/liuxiaoshuai/openBHB
save_dir:  /data2/wangchangmiao/liuxiaoshuai/csbrain/output
model: resnet18
epochs: 300
batch_size: 8
lr: 1e-3
lr_decay: step
lr_decay_rate: 0.9
lr_decay_step: 10
optimizer: adam
momentum: 0.9
weight_decay: 5e-5
train_all: 1
method: hardaware
kernel: gaussian
sigma: 5
trial: 0
tf: none
resume: /data2/wangchangmiao/liuxiaoshuai/csbrain/output/openbhb_models/resnet18_hardaware_adam_tfnone_lr0.0001_step_step10_rate0.9_temp0.1_wd5e-05_bsz8_views2_trainall_True_kernel_gaussian_sigma1.0_trial0/weights.pth
save_freq: 10
lambda_hard: 1.0  # 难样本权重增强幅度
hmax: 1.0  # 截断阈值，控制u的范围
distance_metric: cosine  # 嵌入空间距离度量
gpus: 6
run_name: hardloss_test1
