program: umap_vis.py
data_dir: /data2/wangchangmiao/liuxiaoshuai/openBHB

# 选择可视化的数据划分
# 可选: train / test_internal / test_external
split: test_internal

ckpt: /data2/wangchangmiao/liuxiaoshuai/csbrain/output/openbhb_models/y_aware_experiment_rbf/latest_ckpt.pth
model: resnet18
use_projection: 1

# ========== UMAP Parameters ==========
n_neighbors: 15
min_dist: 0.1
random_state: 0


# ========== Runtime ==========
batch_size: 16
gpus: 2

# ========== Output ==========
out_dir: /data2/wangchangmiao/liuxiaoshuai/csbrain/umap_vis